title: "Matlock's Fight Talk"
description: "Mixed Martial Arts"
baseurl: "" # If the site is in a subdirectory, specify it (e.g., "/blog")
url: "https://matlockft.github.io" # Update with your actual GitHub Pages URL

theme: minima # You can change this to a different Jekyll theme or set to null for custom styles

# Navigation Links
nav:
  - name: Home
    link: /
  - name: Analysis
    link: /analysis
  - name: Scorecard
    link: /scorecard/index.html

plugins:
  - jekyll-feed
  - jekyll-seo-tag
